apiVersion: v1
kind: Template
metadata:
  name: api-services-pipeline

parameters:
- name: PROJECT_NAME
  description: Project Name
  displayname: Project Name
  required: true
  value: workshop
- name: APP_NAME
  description: The name assigned to all of the application objects defined in this template.
  displayName: Application Name
  required: true
  value: zipkin-server
- name: GIT_SOURCE_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
  value: https://github.com/platform-guild/openshift-workshop.git
- name: GIT_SOURCE_REF
  description: The source Ref for the application
  displayName: Source Ref
  required: true
  value: master
- name: APP_PORT
  description: Application server port
  displayName: Server Port
  required: true
  value: "9000"
- name: APP_ENV
  description: Application running environment
  displayName: App Environment
  required: true
  value: dev

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec: {}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}-sti
    name: ${APP_NAME}-sti
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    runPolicy: Serial
    strategy:
      type: Source
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: service-sti-builder:latest
        env:
        - name: APP_NAME
          value: ${APP_NAME}
    source:
      type: Git
      git:
        uri: ${GIT_SOURCE_URL}
        ref: ${GIT_SOURCE_REF}
    triggers:
    - type: ImageChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${PROJECT_NAME}/${APP_NAME}
          imagePullPolicy: Always
          name: ${APP_NAME}
          env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: APP_ENV
            value: ${APP_ENV}
          - name: APP_PORT
            value: ${APP_PORT}
          ports:
          - containerPort: ${{APP_PORT}}
            protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /health
              port: ${{APP_PORT}}
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: ${{APP_PORT}}
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
        containerNames:
        - ${APP_NAME}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: ${APP_PORT}-tcp
      port: ${{APP_PORT}}
      protocol: TCP
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    type: ClusterIP
